gamma:
	sage gamma.sage > gamma.tex
	pdflatex gamma

besselj:
	sage besselj.sage > besselj.tex
	pdflatex besselj

bessely:
	sage bessely.sage > bessely.tex
	pdflatex bessely

all: gamma besselj bessely